### ISSUE TITLE
StartService FAILED with error 4294967201 and while iam launching emulator "the emulator process for avd has been terminated"

### ISSUE THREAD

**Issue by gcsujith** [google/android-emulator-hypervisor-driver#83]
Android SDK is up to date.
Running Android Emulator Hypervisor Driver for AMD Processors installer
[SC] ControlService FAILED 1062:

The service has not been started.

[SC] DeleteService SUCCESS
[SC] StartService FAILED with error 4294967201.
Android Emulator Hypervisor Driver for AMD Processors installation failed. To install Android Emulator Hypervisor Driver for AMD Processors follow the instructions found at: https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors
Done

**Comment by bohous04** [comment]
Hi, I have same problem, any solution?

**Comment by gcsujith** [comment]
After following the instructions from https://www.makeuseof.com/windows-11-disable-hyper-v/#:~:text=In%20the%20Windows%20Features%20dialog,both%20options%20and%20click%20OK. issue got resolved.

**Comment by khoatiendao** [comment]
Hey I got the problem like you but I use Laptop HP Window 10. Does it work for me ?

**Comment by marklemay** [comment]
I am getting the exact same errors, but are not resolved with those instructions

**Comment by PrashikPagare** [comment]
> Hey I got the problem like you but I use Laptop HP Window 10. Does it work for me ?

Really!!! Same problmn I have A Laptop of HP Elitebook windows 10. Does it work for me???

**Comment by mainly-abdullah** [comment]
> > Hey I got the problem like you but I use Laptop HP Window 10. Does it work for me ?
> 
> Really!!! Same problmn I have A Laptop of HP Elitebook windows 10. Does it work for me???

same for me i have HP Probook

**Comment by JeffCodes85** [comment]
I'm on Lenovo Legion Y520 laptop running Windows 10 on an Intel i7-7700HQ.

Mine was fixed after the below:
In "Turn Windows features on or off":
Enabled Virtual Machine Platform
Enabled Windows Hypervisor Platform
In BIOS, enabled Intel Virtualization

**Comment by kingcarol1** [comment]
SOLVED: Windows by enabling virtualization in BIOS. there are other proposed solutions as well on the internet if you dont solve it.
