### ISSUE TITLE
Amd android emulator driver for windows 7

### ISSUE THREAD

**Issue by bouterbik** [google/android-emulator-hypervisor-driver#86]
Hello gay's am working on a flutter project in Vscod and I ran into a problem of AMD android emulator driver I tried everything to solve this issue but I didn't come to a solution

**Comment by Taogle2018** [comment]
What is the issue? Any details?

**Comment by bouterbik** [comment]
> What is the issue? Any details?

 First I tried to install android emulator hypervisor driver for AMD processors (am working version 2021) and I got this error message (windows cannot verify the digital signature) and also error other error message (windows requires a digitally signed driver)
![IMG_20230301_181548.jpg](https://user-images.githubusercontent.com/94929394/222215473-bddb8675-0587-4232-8415-6f29abc2c69d.jpg)

![IMG_20230301_180418.jpg](https://user-images.githubusercontent.com/94929394/222215493-6721530f-9a1d-47cb-a264-ef25a7057a96.jpg)

**Comment by Taogle2018** [comment]
What is the version of your Windows?

**Comment by bouterbik** [comment]
> What is the version of your Windows?

Windows 7 
63 bit

**Comment by Taogle2018** [comment]
OK. For Windows 7, you have to stick with 1.7. That's a limitation from Windows signature requirements.
Or you can disable Windows 7 Driver signature enforcement in order to use later version. Press F8 to access the advanced boot options when booting Windows 7, if I remember correctly.

**Comment by bouterbik** [comment]
Unfortunately doesn't work
