### ISSUE TITLE
[Feature request] Add ARM64 support

### ISSUE THREAD

**Issue by kristibektashi** [google/android-emulator-hypervisor-driver#89]
This could be useful for the people that use Windows to develop Android software and have an ARM64 machine, but don't want to use Hyper-V for various reasons.

**Comment by kristibektashi** [comment]
Also, most (if not all) Android devices use ARM64 processors, so it makes more sense for those who have an ARM64 device to use it for developing Android programs rather than an x86 device that they may have

**Comment by kristibektashi** [comment]
Closing this as a duplicate of #85

**Comment by kristibektashi** [comment]
Closing as a duplicate of #85

**Comment by jaldaadithya** [comment]
Team, Are you planning to support ARM64 arch ?. If yes please let us know the timeline. Thank you.

**Comment by jaldaadithya** [comment]
> Team, Are you planning to support ARM64 arch ?. If yes please let us know the timeline. Thank you.

Can we build ourselves and place it in the sdk location ?
